# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib mcpower, .registration = TRUE
NULL

#' Spike probe — returns the engine's view of the thread count machinery is wired.
engine_r_ping <- function() .Call(wrap__engine_r_ping)

#' Configure the rayon thread pool used by `find_power` / `find_sample_size`.
#' Must be called before any engine invocation; a second call raises an error
#' because the pool is already initialised. Mirrors `mcpower._engine.set_n_threads(n)`.
set_n_threads <- function(n) .Call(wrap__set_n_threads, n)

#' Run the debug introspection pipeline for a single scenario.
#'
#' * `contracts`       — msgpack `raw` vector produced by `build_contract_from_spec`.
#' * `scenario_index`  — 0-based index into the `Vec<SimulationContract>`.
#' * `seed`            — RNG base seed (f64 in R; cast to u64).
#' * `n`               — sample size for this debug run.
#' * `n_sims`          — number of simulations to run.
#' * `stage_*`         — booleans controlling which stages to compute.
#'
#' Returns a named list with fields `input`, `data`, `dispatch`, `stats`,
#' `crit`, `power` (each NULL when the stage was not requested or not available).
debug_report <- function(contracts, scenario_index, seed, n, n_sims, stage_input, stage_data, stage_dispatch, stage_stats, stage_crit) .Call(wrap__debug_report, contracts, scenario_index, seed, n, n_sims, stage_input, stage_data, stage_dispatch, stage_stats, stage_crit)

#' Fit a provided dataset with the configured solver (the `data → results`
#' path). `design` is column-major (R `as.numeric(matrix)` order). Pass an
#' empty `cluster_ids` (`integer(0)`) for non-clustered designs.
#'
#' Returns a named list: `betas` (numeric, length ncol), `design_columns`
#' (character), `converged` (logical), `targets` (list of per-target lists with
#' `target_index`, `target_label`, `beta`, `se`, `statistic`, `statistic_kind`,
#' `critical_value`, `alpha`, `df`, `two_sided`).
debug_load_data <- function(contracts, scenario_index, seed, design, nrow, ncol, outcome, cluster_ids, wald_se) .Call(wrap__debug_load_data, contracts, scenario_index, seed, design, nrow, ncol, outcome, cluster_ids, wald_se)

#' Build the whole `Vec<SimulationContract>` as a single msgpack blob,
#' parametrising outcome_kind + estimator + intercept + clusters at the call
#' site.  Mirrors `engine-py/src/spec_builder_bridge.rs` `build_contract_from_spec`.
#'
#' Returns a named List with elements:
#'   * `names`     — character vector of scenario names
#'   * `contracts` — raw vector (msgpack-encoded `Vec<SimulationContract>`)
#'   * `skeleton`  — JSON string of the index-only `EffectSkeleton` (β-column
#'                   aligned), so the R frontend names results from it + its own
#'                   label store instead of re-deriving the factor layout.
#'
#' `outcome_kind` is one of `"continuous"` | `"binary"`.
#' `estimator`    is one of `"ols"` | `"glm"` | `"mle"`.
build_contract_from_spec <- function(json, outcome_kind, estimator, intercept, clusters_json) .Call(wrap__build_contract_from_spec, json, outcome_kind, estimator, intercept, clusters_json)

#' Parse a model formula string into a JSON string.
#'
#' Returns a JSON object:
#'   `{"dependent": str, "predictors": [str], "terms": [...], "random_effects": [...]}`
#' `terms` items have shape `{"kind": "main", "name": str}` or `{"kind": "interaction", "vars": [str]}`.
#' `random_effects` items have shape `{"kind": "intercept", "group": str, "parent": str|null}` or
#' `{"kind": "slope", "group": str, "vars": [str]}`.
#'
#' Raises an error on syntax errors or unsupported constructs.
#' Mirrors `engine-py/src/spec_builder_bridge.rs` `parse_formula`.
parse_formula <- function(input) .Call(wrap__parse_formula, input)

#' Parse an assignment string (variable types / correlations / effects) into a JSON string.
#'
#' `kind` is one of `"variable_type"`, `"correlation"`, `"effect"`.
#' `known_json` is a JSON object with keys `"predictors": [str]` and `"interaction_terms": [str]`.
#'
#' Returns a JSON object `{"items": [{"key": ..., "value": ...}, ...], "errors": [str, ...]}`.
#' `key` is `{"name": str}` or `{"pair": [str, str]}`.
#' `value` is `{"variable_type": str}` | `{"correlation": f64}` | `{"effect": f64}`.
#' Per-item failures appear in `errors`; only top-level malformed input raises an error.
#' Mirrors `engine-py/src/spec_builder_bridge.rs` `parse_assignments`.
parse_assignments <- function(input, kind, known_json) .Call(wrap__parse_assignments, input, kind, known_json)

#' Synthetic-distribution name → integer code table as a JSON object string.
#' R parses and caches it (`zzz.R`); single source of truth.
dist_codes <- function() .Call(wrap__dist_codes)

#' Residual-distribution name → integer code table as a JSON object string.
#' See [`dist_codes`].
residual_codes <- function() .Call(wrap__residual_codes)

#' Random-effect distribution name → integer code table as a JSON object
#' string (normal/heavy_tailed — the RE knob's own vocabulary). See
#' [`dist_codes`].
re_dist_codes <- function() .Call(wrap__re_dist_codes)

#' Build the canonical effect-recovery design from a `LinearSpec` JSON whose
#' `upload.columns` carry the typed (coded) upload columns. Returns a named list
#' `list(design_flat=<dbl>, semantic_names=<chr>, ncol=<int>)`; the host feeds
#' `design_flat` to `debug_load_data`. Single-sources the design assembly.
build_recovery_design <- function(spec_json) .Call(wrap__build_recovery_design, spec_json)

#' Z-score a slice with population SD (ddof=0) via the shared engine helper —
#' the single source the host uses to scale the outcome for OLS recovery.
standardize_continuous <- function(values) .Call(wrap__standardize_continuous, values)

#' Split a comma-separated assignment string at top-level commas (parens
#' suppress splitting), trimming each segment and dropping empties. The shared
#' splitter the host correlation/effect normalisers bind to. Errors on
#' unbalanced parentheses.
split_assignments <- function(input) .Call(wrap__split_assignments, input)

#' Run a power simulation for all scenarios encoded in `contracts` (a msgpack
#' `raw` vector produced by `build_contract_from_spec`).
#'
#' * `sample_size` — sample size to evaluate.
#' * `n_sims`      — number of Monte-Carlo replications.
#' * `base_seed`   — f64 in R (all R numerics are f64); cast to u64.
#' * `progress`    — an R callback `(current, total)`, or `NULL` for silent.
#'   Events are delivered on the R main thread; Ctrl-C / Escape cancels the run
#'   (see `progress.rs`).
#'
#' Returns a named list mirroring the Python dict shape:
#' `list(scenarios = <named list>, comparison = list())`.
find_power <- function(contracts, sample_size, n_sims, base_seed, progress) .Call(wrap__find_power, contracts, sample_size, n_sims, base_seed, progress)

#' Test-only seam for the cancellation path. Identical to [`find_power`] but
#' flips the `CancellationToken` *before* the engine starts, so the run returns
#' `OrchestratorError::Cancelled` at its first checkpoint and `orchestrator_err`
#' maps it to the "cancelled by user" R error. Lets testthat verify the
#' cancel→error wiring without an interactive SIGINT (the live Ctrl-C path,
#' which flips the same token via `R_CheckUserInterrupt`, is exercised
#' manually). Surfaced as `mcpower:::find_power_precancelled`.
find_power_precancelled <- function(contracts, sample_size, n_sims, base_seed) .Call(wrap__find_power_precancelled, contracts, sample_size, n_sims, base_seed)

#' Run a sample-size search (grid) for all scenarios encoded in `contracts`.
#'
#' * `target_power`      — desired power threshold (0..1).
#' * `lo` / `hi`         — search bounds (sample sizes).
#' * `n_sims`            — Monte-Carlo replications per N point.
#' * `base_seed`         — f64 in R; cast to u64.
#' * `method`            — `"grid"` (the only supported method).
#' * `by`                — grid step size / point count (required).
#' * `by_kind`           — `"fixed"` (step) or `"auto"` (point count); default `"fixed"`.
#' * `mode`              — `"linear"` or `"log"` (default `"linear"`).
#' * `tol_n`             — accepted for API compatibility; unused.
#' * `progress`          — an R callback `(current, total)`, or `NULL` for
#'   silent. Events are delivered on the R main thread; Ctrl-C / Escape cancels
#'   the run (see `progress.rs`).
#'
#' Returns a named list mirroring the Python dict shape:
#' `list(scenarios = <named list>, comparison = list())`.
find_sample_size <- function(contracts, target_power, lo, hi, n_sims, base_seed, method, by, by_kind, mode, tol_n, progress) .Call(wrap__find_sample_size, contracts, target_power, lo, hi, n_sims, base_seed, method, by, by_kind, mode, tol_n, progress)

#' Test-only seam for the internal-error path. Panics inside the engine
#' boundary so testthat can assert the caught panic surfaces as an R error
#' carrying the report hint (mirrors engine-py's `panic_for_test`). Surfaced as
#' `mcpower:::panic_for_test`.
panic_for_test <- function() .Call(wrap__panic_for_test)

#' Return the embedded `configs/config.json` as a JSON string. R parses it
#' with jsonlite and caches it in `.onLoad` (`zzz.R`). Single source of truth.
config <- function() .Call(wrap__config)

#' Return the embedded `configs/scenarios.json` (alias/flat/object-keyed) as a
#' JSON string. R parses it with jsonlite and caches it (`zzz.R` `.scenario_defaults()`).
#' Single source of truth for default scenario configs; the R port keeps no copy.
scenarios <- function() .Call(wrap__scenarios)

#' Ordered named list of (key → spec) pairs for a find_power result.
#'
#' `envelope_json` is produced by the R side via `jsonlite::toJSON(...)`.
#' The envelope `scenarios` array must contain objects with a `"label"` field
#' plus `power` and `ci` carrying the displayed arrays (R caller selects
#' corrected vs uncorrected before calling). Scenarios are rendered in array
#' order — no alphabetical sorting is applied.
#'
#' Returns a named R list (names = block keys, values = Vega-Lite v5 JSON strings).
power_plot_set_json <- function(envelope_json, show_ci, target_power_line) .Call(wrap__power_plot_set_json, envelope_json, show_ci, target_power_line)

#' Ordered named list of (key → spec) pairs for a find_sample_size result.
#'
#' `envelope_json` contains `scenarios` as an ordered array of objects (each
#' with a `"label"` field) with one row per N point in `power` / `ci`, and
#' `histogram` carrying the corrected joint-significance histogram. Scenarios
#' are rendered in array order — no alphabetical sorting is applied.
#' Block order mirrors `sample_size_plot_set` (curve, at_least_k, exactly_k, …).
#'
#' Returns a named R list (names = block keys, values = Vega-Lite v5 JSON strings).
sample_size_plot_set_json <- function(envelope_json, show_ci, target_power_line) .Call(wrap__sample_size_plot_set_json, envelope_json, show_ci, target_power_line)

#' Return the embedded theme JSON for `name`.
plot_theme <- function(name) .Call(wrap__plot_theme, name)

#' The embedded theme names.
list_plot_themes <- function() .Call(wrap__list_plot_themes)

#' The embedded CDN HTML template. Contains a `{{SPECS}}` placeholder that
#' the R host replaces with a JSON array of Vega-Lite spec objects.
plot_html_template <- function() .Call(wrap__plot_html_template)

# nolint end
