import { describe, it, expect } from 'vitest';
import { generatePoissonScript } from './script-generator-poisson';
import type { AppSpec } from './app-spec';

// All-default run config: alpha 0.05, target_power 0.8, n_sims 1600 (ols default), seed 2137.
function samplePoissonSpec(): AppSpec {
  return {
    family: 'poisson',
    parsed_formula: { outcome: 'y', predictors: ['x1', 'x2'], interaction_terms: [] },
    var_types: [
      { kind: 'numeric', name: 'x1' },
      { kind: 'binary', name: 'x2', binary_proportion: 0.4 },
    ],
    effects: [
      { name: 'x1', value: 0.3 },
      { name: 'x2', value: 0.2 },
    ],
    correlations: null,
    alpha: 0.05,
    target_power: 0.8,
    n_sims: 1600,
    seed: 2137,
    tests: { kind: 'all' },
    correction: 'none',
    scenarios: [],
    csv: null,
    report_overall: true,
    contrasts: [],
    baseline_rate: 2.0,
  };
}

describe('generatePoissonScript', () => {
  it('emits family="poisson" and set_baseline_rate (not probability)', () => {
    const out = generatePoissonScript(samplePoissonSpec(), 'find-power', { sample_size: 80 });
    expect(out).toContain('from mcpower import MCPower');
    expect(out).toContain('MCPower("y = x1 + x2", family="poisson")');
    expect(out).toContain('model.set_baseline_rate(2)');
    expect(out).not.toContain('set_baseline_probability');
    expect(out).toContain('model.find_power(');
    expect(out).toContain('sample_size=80,');
  });

  it('raises a type-guard error when called with a non-poisson spec', () => {
    const linearSpec = { ...samplePoissonSpec(), family: 'linear' } as unknown as AppSpec;
    expect(() => generatePoissonScript(linearSpec, 'find-power', { sample_size: 80 })).toThrow();
  });

  it('generates an R script', () => {
    const out = generatePoissonScript(samplePoissonSpec(), 'find-power', { sample_size: 100 }, 'r');
    expect(out).toContain('library(mcpower)');
    expect(out).toContain('family = "poisson"');
    expect(out).toContain('model$set_baseline_rate(');
    expect(out).not.toContain('model.'); // no Python syntax leaked
  });

  // Pins the exact generated text so a later de-duplication of the poisson/logit
  // generators (they share every block except the family token and the baseline
  // setter) cannot silently change what a Poisson scenario produces.
  it('emits the exact pinned Python script', () => {
    const out = generatePoissonScript(samplePoissonSpec(), 'find-power', { sample_size: 80 });
    expect(out).toBe(
      '# Generated by mcpower (app)\n# Reproduce with: pip install mcpower\n\nfrom mcpower import MCPower\n\nmodel = MCPower("y = x1 + x2", family="poisson")\nmodel.set_variable_type("x2=(binary,0.4)")\nmodel.set_effects("x1=0.3, x2=0.2")\nmodel.set_baseline_rate(2)\n\nresult = model.find_power(\n    sample_size=80,\n)\n',
    );
  });

  it('emits the exact pinned R script', () => {
    const out = generatePoissonScript(samplePoissonSpec(), 'find-power', { sample_size: 100 }, 'r');
    expect(out).toBe(
      '# Generated by mcpower (app)\n# Reproduce with: install.packages("mcpower", repos = "https://r.mcpower.app")\n\nlibrary(mcpower)\n\nmodel <- MCPower$new("y ~ x1 + x2", family = "poisson")\nmodel$set_variable_type("x2=(binary,0.4)")\nmodel$set_effects("x1=0.3, x2=0.2")\nmodel$set_baseline_rate(2)\n\nresult <- model$find_power(\n    sample_size=100,\n)\n',
    );
  });
});
