// Generates reproducible MCPower snippets for linear family specs; exports shared
// helpers reused by logit, anova, and mixed generators.
// NOTE: Exports helpers reused by script-generator-{logit,anova,mixed}.ts; shared call-structure changes must apply to all four.
import type { AppSpec, LinearSpec, VarType, CorrectionMethod } from './app-spec';
import type { SampleSizeMethod } from './result';
import { SIMULATION } from '$lib/configs/app-config';

export interface ScriptParams {
  sample_size?: number;
  bounds?: [number, number];
  method?: SampleSizeMethod;
}

export type ScriptLanguage = 'python' | 'r';

/** Per-language surface syntax. Named arguments (`name=value`) are valid in both
 *  Python kwargs and R named args, so only header/import/constructor/call
 *  separator differ. */
export interface Lang {
  header: string[];
  importLines: string[];
  construct: (formula: string, family?: string) => string;
  call: (method: string, arg: string) => string;
  resultOpen: (fn: string) => string;
}

export function langFor(language: ScriptLanguage): Lang {
  if (language === 'r') {
    return {
      header: [
        '# Generated by mcpower (app)',
        '# Reproduce with: install.packages("mcpower", repos = "https://pawlenartowicz.r-universe.dev")',
      ],
      importLines: ['library(mcpower)'],
      construct: (formula, family) =>
        `model <- MCPower$new("${formula}"${family ? `, family = "${family}"` : ''})`,
      call: (m, a) => `model$${m}(${a})`,
      resultOpen: (fn) => `result <- model$${fn}(`,
    };
  }
  return {
    header: ['# Generated by mcpower (app)', '# Reproduce with: pip install mcpower'],
    importLines: ['from mcpower import MCPower'],
    construct: (formula, family) =>
      `model = MCPower("${formula}"${family ? `, family="${family}"` : ''})`,
    call: (m, a) => `model.${m}(${a})`,
    resultOpen: (fn) => `result = model.${fn}(`,
  };
}

/** Map app CorrectionMethod to the string both ports' find_* accept.
 *  'none' signals "omit the argument" — Python rejects the literal string 'none'. */
export function toPortCorrection(c: CorrectionMethod): string {
  if (c === 'benjamini_hochberg') return 'bh';
  if (c === 'tukey_hsd') return 'tukey';
  return c;
}

/** Run-config setter lines, omitting values equal to the port defaults (both
 *  ports embed the same configs/config.json). set_power takes PERCENT (80, not 0.8). */
export function buildConfigLines(
  s: { alpha: number; target_power: number; n_sims: number; seed: number },
  simsDefault: number,
  lang: Lang,
): string[] {
  const lines: string[] = [];
  if (s.alpha !== SIMULATION.alpha) lines.push(lang.call('set_alpha', String(s.alpha)));
  if (s.target_power !== SIMULATION.target_power)
    lines.push(lang.call('set_power', String(s.target_power * 100)));
  if (s.n_sims !== simsDefault) lines.push(lang.call('set_simulations', String(s.n_sims)));
  if (s.seed !== SIMULATION.seed) lines.push(lang.call('set_seed', String(s.seed)));
  return lines;
}

/** The find_power / find_sample_size call block, shared by every family generator.
 *  Lines that restate a port default (bounds 30/200, by auto, correction none)
 *  are omitted. */
export function buildFindCallLines(
  lang: Lang,
  mode: 'find-power' | 'find-sample-size',
  params: ScriptParams,
  testsArg: string | null,
  correction: string,
): string[] {
  const lines: string[] = [];
  if (mode === 'find-power') {
    lines.push(lang.resultOpen('find_power'));
    lines.push(`    sample_size=${params.sample_size ?? 100},`);
  } else {
    lines.push(lang.resultOpen('find_sample_size'));
    const [lo, hi] = params.bounds ?? [SIMULATION.sample_size_bounds.from, SIMULATION.sample_size_bounds.to];
    if (lo !== SIMULATION.sample_size_bounds.from) lines.push(`    from_size=${lo},`);
    if (hi !== SIMULATION.sample_size_bounds.to) lines.push(`    to_size=${hi},`);
    if (params.method && 'Grid' in params.method) {
      const b = params.method.Grid.by;
      if (typeof b === 'object' && b !== null && 'Fixed' in b) lines.push(`    by=${b.Fixed},`);
      // Auto is the default — omit
    }
  }
  if (testsArg !== null) lines.push(`    target_test="${testsArg}",`);
  if (correction !== 'none') lines.push(`    correction="${correction}",`);
  lines.push(')');
  return lines;
}

/** Reconstruct formula string from ParsedFormula. Separator is `=` for Python,
 *  `~` for R. */
function buildFormulaString(spec: LinearSpec, sep: string = '='): string {
  const { outcome, predictors, interaction_terms } = spec.parsed_formula;
  const parts: string[] = [...predictors];
  for (const terms of interaction_terms) {
    parts.push(terms.join(':'));
  }
  return `${outcome} ${sep} ${parts.join(' + ')}`;
}

/** Build the set_variable_type argument string in the engine assignment grammar
 *  (`x=(binary,0.3)`, `g=(factor,0.4,0.3,0.3)`, `x=right_skewed`). Returns null
 *  when every predictor is a default normal. */
export function buildVarTypeString(var_types: VarType[]): string | null {
  const entries: string[] = [];
  for (const v of var_types) {
    if (v.kind === 'numeric') {
      if (v.distribution && v.distribution !== 'normal') {
        entries.push(`${v.name}=${v.distribution}`);
      }
    } else if (v.kind === 'binary') {
      entries.push(`${v.name}=(binary,${v.binary_proportion})`);
    } else {
      entries.push(`${v.name}=(factor,${v.factor_proportions.join(',')})`);
    }
  }
  return entries.length > 0 ? entries.join(', ') : null;
}

/** Translate an app effect name to the port naming: custom factor level labels
 *  become 1-based level numbers (`origin[Japan]` → `origin[2]`), since the
 *  string APIs have no label vocabulary for synthetic factors. Interaction
 *  segments translate independently; names already in numeric form pass through. */
export function pyEffectName(name: string, var_types: VarType[]): string {
  return name
    .split(':')
    .map((seg) => {
      const m = seg.match(/^(.+?)\[(.+)\]$/);
      if (!m) return seg;
      const vt = var_types.find((v) => v.kind === 'factor' && v.name === m[1]);
      if (!vt || vt.kind !== 'factor' || !vt.factor_labels || vt.factor_labels.length === 0) {
        return seg;
      }
      const idx = vt.factor_labels.indexOf(m[2]!);
      return idx === -1 ? seg : `${m[1]}[${idx + 1}]`;
    })
    .join(':');
}

/** Lines for the Model "More options" knobs (`outcome_options`). Only structural
 *  fields are on the wire; magnitudes (λ, heterogeneity, df) are scenario-driven. */
export function buildOutcomeOptionLines(spec: LinearSpec, lang: Lang = langFor('python')): string[] {
  const o = spec.outcome_options;
  if (!o) return [];
  const lines: string[] = [];
  if (o.residual_distribution) {
    lines.push(lang.call('set_residual_distribution', `"${o.residual_distribution}"`));
  }
  if (o.heteroskedasticity_driver) {
    lines.push(lang.call('set_heteroskedasticity_driver', `var="${o.heteroskedasticity_driver}"`));
  }
  return lines;
}

/** Build the set_correlations argument string. Returns null if none or all-zero. */
export function buildCorrelationsString(spec: LinearSpec): string | null {
  if (!spec.correlations) return null;
  const { names, values } = spec.correlations;
  const pairs: string[] = [];
  for (let i = 0; i < names.length; i++) {
    for (let j = i + 1; j < names.length; j++) {
      const v = values[i]?.[j];
      if (v !== undefined && v !== 0) {
        pairs.push(`${names[i]},${names[j]}=${v}`);
      }
    }
  }
  if (pairs.length === 0) return null;
  return pairs.join(', ');
}

/**
 * The `target_test="..."` DSL token string for the `find_*` call, or null when
 * the selection is the default (tests.kind === 'all' AND report_overall === true
 * AND no contrasts). Reads only fields shared by every LinearSpec-derived spec,
 * so Mixed reuses it.
 */
export function buildTestsArg(spec: LinearSpec): string | null {
  const contrasts = spec.contrasts ?? [];
  const useTargetTest =
    contrasts.length > 0 ||
    spec.tests.kind === 'effects' ||
    spec.report_overall === false;
  if (!useTargetTest) {
    return null;
  }

  const tokens: string[] = [];
  if (spec.tests.kind === 'all' && spec.report_overall === true) {
    // "all" keyword covers omnibus + every β; append contrasts after
    tokens.push('all');
  } else if (spec.tests.kind === 'all' && spec.report_overall === false) {
    // Every β but no omnibus — enumerate explicitly
    for (const eff of spec.effects) {
      tokens.push(pyEffectName(eff.name, spec.var_types));
    }
  } else if (spec.tests.kind === 'effects') {
    if (spec.report_overall) tokens.push('overall');
    for (const name of spec.tests.names) {
      tokens.push(pyEffectName(name, spec.var_types));
    }
  }
  for (const [pos, neg] of contrasts) {
    tokens.push(`${pyEffectName(pos, spec.var_types)} vs ${pyEffectName(neg, spec.var_types)}`);
  }
  return tokens.join(', ');
}

export function generateLinearScript(
  spec: AppSpec,
  mode: 'find-power' | 'find-sample-size',
  params: ScriptParams,
  language: ScriptLanguage = 'python',
): string {
  if (spec.family !== 'linear') {
    throw new Error('generateLinearScript called with non-linear spec');
  }

  const s: LinearSpec = spec;

  if (!s.parsed_formula?.outcome) {
    return '# Cannot generate script: missing formula\n';
  }

  const lang = langFor(language);
  const lines: string[] = [];

  for (const h of lang.header) lines.push(h);
  lines.push('');

  for (const imp of lang.importLines) lines.push(imp);
  lines.push('');

  // Constructor — R uses `~`, Python uses `=`
  const formula = buildFormulaString(s, language === 'r' ? '~' : '=');
  lines.push(lang.construct(formula));

  // Variable types — only when at least one non-numeric
  const varTypeStr = buildVarTypeString(s.var_types);
  if (varTypeStr !== null) {
    lines.push(lang.call('set_variable_type', `"${varTypeStr}"`));
  }

  // Effects
  const effectsStr = s.effects
    .map((e) => `${pyEffectName(e.name, s.var_types)}=${e.value}`)
    .join(', ');
  lines.push(lang.call('set_effects', `"${effectsStr}"`));

  // Correlations — only when present and non-zero
  const corrStr = buildCorrelationsString(s);
  if (corrStr !== null) {
    lines.push(lang.call('set_correlations', `"${corrStr}"`));
  }

  // Outcome-level knobs — only non-neutral values exist on the wire
  for (const line of buildOutcomeOptionLines(s, lang)) lines.push(line);

  // Run-config setters — omit values equal to port defaults; set_power takes percent
  for (const line of buildConfigLines(s, SIMULATION.n_sims.ols, lang)) lines.push(line);

  lines.push('');

  // find_power / find_sample_size call
  const correction = toPortCorrection(s.correction);
  const testsArg = buildTestsArg(s);
  for (const line of buildFindCallLines(lang, mode, params, testsArg, correction)) lines.push(line);

  return lines.join('\n') + '\n';
}
