"""Reference fit for the random-intercept LME case.

Generates the canonical N=60, 6 clusters of 10, P=3 (intercept + 2 covariates)
case from the plan and fits it with statsmodels.MixedLM(..., reml=True).
Prints the fitted fixed effects (β̂) and Wald t² values for the two
non-intercept targets to 8 significant figures so they can be pasted into
the Rust integration test (`lme_fit_matches_statsmodels_mixedlm_reference`).

Cluster layout: interleaved,
`cluster_ids[i] = i % n_clusters`. This matches what data_gen.rs emits.

Random structure:
    u ~ N(0, sqrt(0.4))    one per cluster (so τ² = 0.4)
    ε ~ N(0, 1)
    true β = [0.0, 0.5, 0.3]
"""

import warnings

import numpy as np
import statsmodels.api as sm
from statsmodels.tools.sm_exceptions import ConvergenceWarning

# Reference fit on a well-conditioned case — none expected, but stay quiet.
warnings.filterwarnings("ignore", category=ConvergenceWarning)


def main():
    rng = np.random.default_rng(42)
    N = 60
    n_clusters = 6
    cluster_size = N // n_clusters  # = 10
    P = 3  # intercept + 2 standard-normal covariates

    # Interleaved cluster ids (row i -> cluster i mod n_clusters).
    cluster_ids = np.array([i % n_clusters for i in range(N)], dtype=np.int64)

    # Design matrix: intercept + 2 standard normals.
    x1 = rng.standard_normal(N)
    x2 = rng.standard_normal(N)
    X = np.column_stack([np.ones(N), x1, x2])

    # True parameters: β = [0.0, 0.5, 0.3]; τ² = 0.4; σ² = 1.0.
    true_beta = np.array([0.0, 0.5, 0.3])
    tau = np.sqrt(0.4)
    u = rng.standard_normal(n_clusters) * tau
    eps = rng.standard_normal(N)
    y = X @ true_beta + u[cluster_ids] + eps

    md = sm.MixedLM(endog=y, exog=X, groups=cluster_ids,
                    exog_re=np.ones((N, 1)))
    fit = md.fit(reml=True)

    # Fixed effects + Wald t² for the two non-intercept targets.
    # statsmodels returns `params` = [fe_0, fe_1, fe_2, scale_re] for a
    # single-RE model; the fixed-effect betas are `fit.fe_params`. The
    # Wald-t values are `fit.tvalues[:P]` (last entry is for the variance
    # component, which we ignore).
    betas = np.asarray(fit.fe_params, dtype=float)
    tvals = np.asarray(fit.tvalues, dtype=float)[:P]
    t_sq_all = tvals * tvals  # length P
    # Targets: covariates x1, x2 (indices 1 and 2 — index 0 is intercept).
    t_sq_targets = t_sq_all[1:3]

    # --- Diagnostics ---------------------------------------------------------
    def f(v):
        return repr(float(v))

    def f8(v):
        return f"{float(v):.8g}"

    print("# Input data (numpy default_rng(42), interleaved cluster ids):")
    print(f"# N           = {N}")
    print(f"# P           = {P}")
    print(f"# n_clusters  = {n_clusters}")
    print(f"# cluster_size= {cluster_size}")
    print(f"# true_beta   = {true_beta.tolist()}")
    print(f"# tau^2       = 0.4   (sigma_u = sqrt(0.4))")
    print(f"# sigma^2     = 1.0")
    print()
    print(f"cluster_ids[:12] = {cluster_ids[:12].tolist()}   # (interleaved)")
    print(f"# All ids are i % n_clusters for i in 0..N.")
    print()

    print("# statsmodels MixedLM(reml=True) fit results:")
    print(f"#   fe_params         = {betas.tolist()}")
    print(f"#   bse[:P]           = {np.asarray(fit.bse)[:P].tolist()}")
    print(f"#   tvalues[:P]       = {tvals.tolist()}")
    print(f"#   tvalues^2 [:P]    = {t_sq_all.tolist()}")
    print(f"#   cov_re (tau^2_hat)= {float(np.asarray(fit.cov_re).ravel()[0])!r}")
    print(f"#   scale (sigma^2_hat) = {float(fit.scale)!r}")
    print()

    # --- Final constants -----------------------------------------------------
    print("// ------------------------------------------------------------")
    print("// Paste these into the LME test body")
    print("// Generated by MCPower2/scripts/lme_reference_mixedlm.py")
    print("// Constants pinned to 8 significant figures.")
    print("// ------------------------------------------------------------")
    b_str = ", ".join(f8(b) for b in betas)
    t_str = ", ".join(f8(t) for t in t_sq_targets)
    print(f"let expected_betas: [f64; 3] = [{b_str}];")
    print(f"let expected_t_sq: [f64; 2] = [{t_str}];")
    print()
    print("# Full-precision repr (for cross-check / debugging):")
    print(f"#   expected_betas (16sf) = [{', '.join(f(b) for b in betas)}]")
    print(f"#   expected_t_sq  (16sf) = [{', '.join(f(t) for t in t_sq_targets)}]")


if __name__ == "__main__":
    main()
