# agq_parity.R — L3 B<->C AGQ parity: MCPower run at agq=k vs lme4::glmer(nAGQ=k)
# on the SAME generated bytes, for an AGQ-eligible clustered binary GLMM
# (single grouping, intercept-only RE). Verifies (a) MCPower's AGQ path runs and
# (b) at matched node count k both engines agree on beta MORE tightly than the
# Laplace-vs-Laplace gap — i.e. MCPower's AGQ tracks glmer's AGQ, not just its
# Laplace. Reports measured gaps; freezes data/glmm_agq.golden.rds.
#
# Requires the R port rebuilt with the fit_provided_data nagq fix (introspect.rs)
# and MCPowerDebug$load_data(d, nagq=) (mcpower-debug.R).
suppressMessages({ library(mcpower); library(lme4) })
script_dir <- local({
  fa <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
  if (length(fa)) dirname(normalizePath(sub("^--file=", "", fa[1]))) else getwd()
})
setwd(script_dir)
source("common.R"); source("tolerances.R")

K   <- 5L    # AGQ node count (odd, eligible)
NDR <- 12L   # draws to average the B<->C gap over (glmer few-cluster noise)

# Eligible AGQ case: clustered binary logit GLMM, one grouping, intercept-only RE.
case <- list(
  label = "glmm_agq", family = "logit",
  formula = "y ~ x1 + (1|grp)", effects = "x1=0.5",
  baseline_probability = 0.3,
  cluster = list(var = "grp", ICC = 0.3, n_clusters = 30L, cluster_size = 20L),
  glmer_re = "(1 | g_primary)", agq = K, n = 600L, seed = 4242L
)

# Minimal m4_frame / m4_glmer_formula (rmd-local helpers, replicated for one x-var).
frame <- function(d) {
  cn <- d$columns; nn <- cn
  nn[cn == "intercept"] <- "intercept_col"; nn[cn == "col_1"] <- "x1"
  df <- as.data.frame(d$design); colnames(df) <- nn
  df$y <- d$outcome; df$g_primary <- factor(d$cluster_ids); df
}

gap_at <- function(nagq) {
  gaps <- c()
  for (k in seq_len(NDR)) {
    m <- build_m4_model(case, seed_off = k)   # family="logit" clustered GLMM
    d <- m$create_data(); df <- frame(d)
    rf <- suppressMessages(tryCatch(
      lme4::glmer(y ~ x1 + (1 | g_primary), data = df, family = binomial, nAGQ = nagq),
      error = function(e) NULL))
    if (is.null(rf) || isTRUE(any(grepl("failed to converge|singular",
        unlist(rf@optinfo$conv$lme4$messages))))) next
    fit <- m$load_data(d, nagq = nagq)
    bR <- as.numeric(lme4::fixef(rf))
    gaps <- c(gaps, max(abs(bR - fit$betas)))   # worst |Δβ| over columns, this draw
  }
  gaps
}

cat(sprintf("AGQ parity: MCPower vs glmer on same bytes, %d draws, case %s\n",
            NDR, case$label))
lap <- gap_at(1L)     # Laplace vs glmer-Laplace (baseline gap)
agq <- gap_at(K)      # AGQ(K) vs glmer(nAGQ=K)
cat(sprintf("  Laplace (nagq=1): median worst|Δβ| = %.4f  (n=%d clean draws)\n",
            stats::median(lap), length(lap)))
cat(sprintf("  AGQ (nagq=%d):    median worst|Δβ| = %.4f  (n=%d clean draws)\n",
            K, stats::median(agq), length(agq)))
# Gate: MCPower-AGQ(K) must track glmer(nAGQ=K) within the same GLMM beta band the
# Laplace B<->C uses; AND AGQ should not be WORSE than Laplace (it removes shared bias).
band <- GLMM_TOL$agq_beta_abs
ok <- stats::median(agq) <= band && stats::median(agq) <= stats::median(lap) + 1e-9
cat(sprintf("  band=%.3f  ->  %s\n", band, if (ok) "OK — AGQ tracks glmer(nAGQ=k)" else "*** FAIL ***"))

if (ok) {
  saveRDS(list(label = case$label, agq = K,
               beta_gap_laplace = stats::median(lap),
               beta_gap_agq = stats::median(agq),
               n_draws = NDR, band = band,
               lme4_version = as.character(utils::packageVersion("lme4")),
               mcpower = as.character(utils::packageVersion("mcpower"))),
          file.path("data", "glmm_agq.golden.rds"))
  cat("  frozen data/glmm_agq.golden.rds\n")
}
quit(status = if (ok) 0L else 1L)
